Cleanup useViewportColumns hook
adazzle/react-data-grid pull request #2216
Opened 2020-11-08 17:23 UTC by amanmahajan7

2020-11-08 17:26 UTC, amanmahajan7 commented on src/hooks/useViewportColumns.ts
> +  }, [columnWidths, defaultFormatter, defaultResizable, defaultSortable, minColumnWidth, rawColumns, rawGroupBy, viewportWidth]);
No need to run the hook if `rowGrouper` is changed.

2020-11-09 11:28 UTC, nstepien commented on src/utils/columnUtils.ts
> +export function getSpecifiedWidth<R, SR>(
I think we can move `getSpecifiedWidth` and `clampColumnWidth` into `useViewportColumns.ts`, they're not meant to be used for anything, so no need to "share" them.

2020-11-09 12:01 UTC, nstepien requested changes

2020-11-09 12:01 UTC, nstepien commented on src/hooks/useViewportColumns.ts
> +export function getSpecifiedWidth<R, SR>(
```suggestion
function getSpecifiedWidth<R, SR>(
```

2020-11-09 12:01 UTC, nstepien commented on src/hooks/useViewportColumns.ts
> +export function clampColumnWidth<R, SR>(
```suggestion
function clampColumnWidth<R, SR>(
```

2020-11-09 13:05 UTC, nstepien approved these changes

2020-11-09 13:07 UTC, merged