Allow customizing the key property
adazzle/react-data-grid pull request #2311
Opened 2021-02-22 05:25 UTC by danielpza

Why? This fails:

```tsx
const [selected, setSelected] = new Set<string>([])

<DataGrid selectedRows={selected} onSelectedRowsChange={setSelected} />
```

because onSelectedRowsChange was expected to receive all the properties React.Key has, eg number, which is not possible/desired.

2021-05-11 11:31 UTC, nstepien requested changes
I think it's a good idea.
Can you please also add the generic to the default export, it's at the end of `DataGrid.tsx`.

2021-05-11 11:31 UTC, nstepien commented on src/DataGrid.tsx
> +export interface DataGridProps<R, SR = unknown, K = React.Key> extends SharedDivProps {
```suggestion
export interface DataGridProps<R, SR = unknown, K extends React.Key = React.Key> extends SharedDivProps {
```

2021-05-11 22:58 UTC, nstepien commented
Please also add the generic to the default export at the end of `DataGrid.tsx`, it won't be usable otherwise.

2021-05-11 23:55 UTC, nstepien commented on src/DataGrid.tsx
> +export default forwardRef(DataGrid) as <R, SR = unknown, Key extends React.ReactKey = React.ReactKey>(props: DataGridProps<R, SR, Key> & RefAttributes<DataGridHandle>) => JSX.Element;
```suggestion
export default forwardRef(DataGrid) as <R, SR = unknown, Key extends React.Key = React.Key>(props: DataGridProps<R, SR, Key> & RefAttributes<DataGridHandle>) => JSX.Element;
```

2021-05-11 23:58 UTC, merged

2021-05-12 00:09 UTC, danielpza commented
Thank you! :tada: